### ISSUE TITLE
Login user after registration

### ISSUE THREAD

**Issue by abdelrahman-elkady** [desoukya/SEMS#1]
User is not automatically logged in after account creation as the creation is done on server for default role insertion

**Comment by alihassan0** [comment]
shouldn't this be resolved now @abdelrahman-elkady

**Comment by abdelrahman-elkady** [comment]
still not, Thinking of logging the user in even if the mail is not verified, as he is allowed to login anyways but will be limited until his mail is verified

**Comment by alihassan0** [comment]
@abdelrahman-elkady  is that still happening .. or should I close this ?
